# Generated by Django 5.0.6 on 2024-06-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_points_user_role_review_user_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='app.review'),
        ),
    ]
