# Generated by Django 5.0.6 on 2024-06-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
    ]
