# Generated by Django 5.0.6 on 2024-06-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_review_review_text_remove_user_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
